<?php
/**
 * Created by PhpStorm.
 * User: dzozulya
 * Date: 25.02.17
 * Time: 6:37
 */

namespace app\components\hotels;

/**
 * Config object for Hotelbeds API. Will use in app config.
 * @author D.Zozulya
 */


use yii\base\Component;

class Config extends Component
{
    /**
     * @var
     */
    public $url;
    /**
     * @var
     */
    public $apiKey;
    /**
     * @var
     */
    public $sharedSecret;
    /**
     * @var
     */
    public $timeout;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->timeout = $this->timeout ? $this->timeout : 30;
    }


}