<?php
/**
 * Created by PhpStorm.
 * User: dzozulya
 * Date: 20.03.17
 * Time: 5:50
 */

namespace app\components\hotels\hotel;


use app\components\hotels\ApiClient;
use app\components\hotels\helpers\RoomFacilitiesHelper;
use app\components\hotels\helpers\RoomFacilityHelper;
use app\components\hotels\helpers\RoomImageHelper;
use app\components\hotels\queries\HotelApiQuery;
use yii\base\Component;

class Room extends Component
{

    const IMAGE_URL = 'http://photos.hotelbeds.com/giata/';

    public $date_from;
    public $date_to;
    public $rooms;
    public $name;
    public $adults;
    public $children;
    public $hotelCode;
    public $roomCode;
    public $rates = [];


    private $nights;
    private $rateComment;
    private $facilities = [];
    private $images = [];
    private $hotel;
    private $roomRate;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->roomCode && $this->hotelCode) {
            $this->images = RoomImageHelper::findImages($this->roomCode, $this->hotelCode);
            $this->facilities = RoomFacilitiesHelper::findFacilities($this->hotelCode, $this->roomCode);
            foreach ($this->rates as $rate) {

                $this->roomRate[] = \Yii::createObject([
                    'class' => Rates::className(),
                    'rateKey' => $rate ->rateKey,
                    'rateClass' => $rate->rateClass,
                    'rateType' => $rate->rateType,
                    'netPrice' => $rate->net,
                    'allotment' => $rate->allotment,
                    'rateCommentsId' => $rate->rateCommentsId,
                    'paymentType' => $rate->paymentType,
                    'boardCode' => $rate->boardCode,
                    'boardName' => $rate->boardName,
                    'cancelPrice' => $rate->cancellationPolicies->amount,
                    'cancelDate' => $rate->cancellationPolicies->date

                ]);
            }
        }

    }


    public function getImages()
    {

        return $this->images;
    }

    public function getFacilities()
    {
        return $this->facilities;

    }

    public function getRoomRates()
    {
        return $this->roomRate;
    }


}