<?php
/**
 * Created by PhpStorm.
 * User: dzozulya
 * Date: 12.03.17
 * Time: 22:37
 */

namespace app\modules\main\components\widgets;


use app\components\hotels\ApiClient;
use app\components\hotels\queries\types\AccomodationsQuery;
use yii\bootstrap\Widget;

class Accommodations extends Widget
{
    public $model;
    public $accs;


    private $cache;

    public function init()
    {
        parent::init();
        $this->cache = \Yii::$app->cache;

        $filters = $this->cache->get('accommodations-filters');

        if ($filters !== false && $filters !== null) {
            $this->model = $filters;
        } else {
            $this->model = ApiClient::query(AccomodationsQuery::className())
                ->addParams([
                    'language'=>'ENG',
                    'from' => '1',
                    'to' => '10'
                ])
                ->get()
                ->asArray();

            $this->cache->set('accommodations-filters', $this->model, 1000);
        }

        $this->accs = explode(',', $this->accs);
    }

    public function run()
    {

        parent::run(); // TODO: Change the autogenerated stub

        return $this->render('accommodations', [
           'model' => $this->model['accommodations'],
           'accs' => $this->accs
        ]);
    }
}