<?php
/**
 * Created by PhpStorm.
 * User: dzozulya
 * Date: 22.03.17
 * Time: 10:18
 */

namespace app\modules\main\components\widgets;


use app\components\hotels\helpers\FacilityCssClasses;
use app\components\hotels\helpers\FacilityCssIcons;
use yii\base\Widget;

class RoomFacilities extends Widget
{
    public $facilities;
    private $_classes;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub



    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('room-facilities', [
            'icons' => $this->getClasses()
        ]);
    }

    private function getClasses()
    {
        //dd($this->facilities);
        foreach ($this->facilities as $facility){


            $icon = FacilityCssClasses::icons($facility->description->content);
            if($icon){
                $icons[] = $icon;
            }
        }

        if(isset($icons)) {

            return $icons;
        } else
            return false;

    }

}